### ISSUE TITLE
Recent build's npm packages lacking dist folder

### ISSUE THREAD

**Issue by Toby222** [nextauthjs/adapters#159]
The @next-auth/prisma-adapter npm version 0.5.1 package seems to lack any build output.
Worked arount it by installing version `0.5.0 || ^0.5.2`
https://registry.npmjs.org/@next-auth/prisma-adapter/-/prisma-adapter-0.5.1.tgz
![image](https://user-images.githubusercontent.com/14962962/124085817-b727a680-da50-11eb-98a0-91dcf75afd3a.png)

**Comment by balazsorban44** [comment]
😬 cc @ndom91 Any ideas?

I checked, dist folder is included in the package.json.

**Comment by styxlab** [comment]
Same issue here. When installing `0.5.1` I get the following compile error:
```
./pages/api/auth/[...nextauth].ts:5:31
Type error: Cannot find module '@next-auth/prisma-adapter' or its corresponding type declarations.
```
Downgrading to `0.5.0` works.

**Comment by sachinraja** [comment]
Alll the adapter packages in [the recent publish](https://github.com/nextauthjs/adapters/commit/a42e3236fecdb2265e9f6bc3006959961f948ff6) are empty:
[@next-auth/dynamodb-adapter@0.4.1](https://unpkg.com/browse/@next-auth/dynamodb-adapter@0.4.1/)
[@next-auth/fauna-adapter@0.2.0](https://unpkg.com/browse/@next-auth/fauna-adapter@0.2.0/) (current version v.0.2.1 is ok because it was published after)
[@next-auth/firebase-adapter@0.1.1](https://unpkg.com/browse/@next-auth/firebase-adapter@0.1.1/)
[@next-auth/pouchdb-adapter@0.1.1](https://unpkg.com/browse/@next-auth/pouchdb-adapter@0.1.1/)
[@next-auth/prisma-legacy-adapter@0.1.1](https://unpkg.com/browse/@next-auth/prisma-legacy-adapter@0.1.1/)
[@next-auth/prisma-adapter@0.5.1](https://unpkg.com/browse/@next-auth/prisma-adapter@0.5.1/)
[@next-auth/typeorm-legacy-adapter@0.1.1](https://unpkg.com/browse/@next-auth/typeorm-legacy-adapter@0.1.1/)

**Comment by balazsorban44** [comment]
@sachinraja do you have an insight why we couldn't use the `--since` flag kn builds, and why should we need to build packages that wouldn't be released anyway (haven't changed)?

My understanding was that we could accelerate our pipeline by only doing work for packages that will be released by `lerna publish`

Was I wrong?

**Comment by sachinraja** [comment]
Might be wrong here but doesn't `--since HEAD~` just check if any of the packages have changed since the last comment? Since none of them changed in the last commit before the publish (a simple workflow file change), none of them ran the build command. I'm assuming `lerna publish` based its package diffs on the latest tag, and not the latest commit, so all packages were published, but none were built. This would've been fine because theoretically every commit published before that would've run through CI and instantly been published on the change (and thus have been built too). My guess is that if changes are made to all the packages and pushed to `main`, they will be automatically be built and released.

**Comment by balazsorban44** [comment]
The `lerna publish` command also uses the `--since` tag though, so It shouldn't publishing anything that hasn't been build either :thinking:

What you linked looks promising though! Let us try that :smile:

**Comment by ndom91** [comment]
@issue we just published new `@latest` versions of all adapters from the latest `main` branch code. Should be good to go again. Can you please give the latest release of your adapter a shot? Thanks!

**Comment by sachinraja** [comment]
@balazsorban44  `--since` without a value diffs against the previous git tag. `--since HEAD~` diffs against the previous commit.
