### ISSUE TITLE
Type Error when trying to import the TypeORMLegacyAdapter

### ISSUE THREAD

**Issue by KLewin23** [nextauthjs/adapters#164]
When I try to import the '@next-auth/typeorm-legacy-adapter' like in the readme I get a type error, when I look in the types there's no definition for it either.

![image](https://user-images.githubusercontent.com/26819329/124641071-36b8d980-de86-11eb-81e1-41076a12807f.png)

Also like the NextAuth docs shows when trying to create custom models due to there being no exported adapter there is also no exported models meaning I cant spread them if necessary .

![image](https://user-images.githubusercontent.com/26819329/124641196-551ed500-de86-11eb-9649-a96596aa29b2.png)

**Comment by balazsorban44** [comment]
Hmm. I am not sure why the README looks like that...

The legacy adapters can still be imported directly from `next-auth/adapters`. TypeORM would be:

```js
import Adapters from "next-auth/adapters"

Adapters.TypeORM.Adapter(...)
```

as here: https://next-auth.js.org/adapters/typeorm/typeorm-overview

cc @ndom91 could you update the README?

**Comment by KLewin23** [comment]
Just to check currently the 'next-auth' package uses the '0.0.2-canary.129' version of the adapter which doesn't have the changes added in #87 is my only way to use the newer version to run the code I was already running with a //ts-ignore which does work and wait for nex-auth to update the version they use?

![image](https://user-images.githubusercontent.com/26819329/124659307-b5b90c80-de9c-11eb-99a0-02515f1bc04c.png)

If so that's fine just wanna make sure I'm not missing something obvious.

**Comment by aivar** [comment]
Following the model extension README:

`  adapter: Adapters.TypeORM.Adapter(
    // The first argument should be a database connection string or TypeORM config object
    { type: 'mysql',
      url: dbString
    }, 
    // The second argument can be used to pass custom models and schemas
    {
      models: {
        User: Models.User,
      },
    }
  ),`

creates this error message in the latest version when using ts:

Type '{ User: { model: typeof User; schema: { name: string; target: typeof User; columns: { shortname: EntitySchemaColumnOptions; name?: EntitySchemaColumnOptions; email?: EntitySchemaColumnOptions; image?: EntitySchemaColumnOptions; emailVerified?: EntitySchemaColumnOptions; }; }; }; }' is missing the following properties from type 'TypeORMAdapterModels': Account, Session, VerificationRequestts(2739)

index.d.ts(88, 9): The expected type comes from property 'models' which is declared here on type '{ models?: TypeORMAdapterModels; }'

Can be worked around, but should probably be fixed in the adapter type def.

**Comment by ndom91** [comment]
@balazsorban44 let's link up on this and clear up the typeorm-legacy instructions / types
