### ISSUE TITLE
Prisma schema in wrong location?

### ISSUE THREAD

**Issue by izaacdb** [nextauthjs/adapters#191]
I'm using a monorepo, containing a server and a nextjs frontend. The prisma schema is ejected to a shared folder so it can be used in several apps and during builds. The shared client is imported via `import {PrismaClient} from '@shared/prisma'`

Folder structure:
````
/server
/frontend/pages/api/auth/[...nextauth].ts
/shared/schema/prisma.schema
````

When I run the frontend using `"@next-auth/prisma-adapter": "^0.5.4",` and `"next-auth": "^3.29.0",` I get this error when clicking "sign in":

````
Error:
Invalid `prisma.user.findUnique()` invocation:
Query engine exited with code 101

thread 'main' panicked at 'Could not open datamodel file ".../frontend/.next/server/pages/api/auth/schema.prisma"', query-engine/query-engine/src/opt.rs:196:53
````

Here I think the adapter is looking in the api file in `.../pages/api/auth` instead of in `./shared/schema`. Is this a bug or is there a way to set this? The typescript seems to only accept undefined for options, and I cannot find any docs for the options.

If I manually copy in the file to the next build directory it works fine.

**Comment by balazsorban44** [comment]
I don't think it's an issue with the adapter. we don't care about where you store your schema file. I'm happy to reopen if you have a reproduction

**Comment by izaacdb** [comment]
I've added a demo project here with the same problem - https://github.com/izaacdb/next-auth-test-case/tree/master

**Comment by balazsorban44** [comment]
I'm not that experienced with Prisma, didn't know the schema has to be in a certain location for it to work. 👀. @ndom91 any ideas?

**Comment by ndom91** [comment]
Hmm as far as I know the schema file has to be in. `/prisma/schema.prisma` in the root. Never used prisma in a mono repo and especially not with shared schema like this, sorry. 

@williamluke4 any ideas?

**Comment by danieldunderfelt** [comment]
I am also running into this. I have a monorepo with multiple apps who use Prisma, and I ma running into many issues. Seems like Prisma is trying to be too clever at times. At first I had the prisma stuff in a dedicated package, but after reading this thread, the best solution I found is to move the prisma folder into the root and then cp the schema.prisma file in the build script of all apps that use Prisma.

I would love to see improvements in this area, and a configurable prisma schema path is a good start. Ideally Prisma would look for the schema _relative to the main file of the package it is in_, so that Prisma can be put into a package and installed into any apps that want to use it. Currently the schema path resolution is dumb as a rock, it tried to look for the schema in a random folder at one point.

**Comment by balazsorban44** [comment]
As mentioned above, this sounds like an upstream issue to me. We don't really care where your `prisma` client is generated, as long as it has the expected methods available. You could ask on their repo.
