### ISSUE TITLE
Accept newest version of MongoDB driver `4.1.0`

### ISSUE THREAD

**Issue by italodeandra** [nextauthjs/adapters#192]
### Description 📓

The version 4 of the MongoDB driver is out.

### Error message ☕️

```
Error: optional dependency [mongodb] found but version [4.1.0] did not satisfy constraint [^3.5.9]
```

**Comment by italodeandra** [comment]
The newest version of the driver looks really good. Before v4 the norm was to use Mongoose. But Mongoose is a ODM (similar to MikroORM and TypeORM), and I'm not sure to what point does NextAuth need that much features.

In my opinion we should be fine by using only the newest driver.

**Comment by balazsorban44** [comment]
Question @italodeandra. Since mongoDB is not relational, I was wondering what would be a better structure for the data.

1. A single Users collection, where on each user we store an `accounts` and `sessions` array
2. or separate collections for Users, Accounts and Sessions, and connect them by a `userId` field.

Or either of these would be alright?

**Comment by italodeandra** [comment]
I would suggest the second one to keep the idea of "relation" and avoid difference if someone tries to switch from one database provider to another while (somehow) keeping the data.

MongoDB you usually use the first option if the "sub-collection" is a primitive or something that would not grow (like user additional emails), but not for sessions since they can grow big. Even accounts I would suggest to also have a separate collection since it's not primitive, but that is just my preference.

**Comment by balazsorban44** [comment]
@italodeandra I created an initial release here: https://www.npmjs.com/package/@next-auth/mongodb-adapter

Could you test it out? It requires `next-auth@4.0.0-next.24`. Some preliminary migration docs can be found here https://docs-nextauthjs.vercel.app/getting-started/upgrade-v4

I would be very grateful if you could have a look at the PR at #193 as well if you have the capacity. :pray: 

One thing, in particular, I struggle with is how to handle connections properly. Other solutions like Prisma or Fauna handle all that automatically, but in the case of MongoDB, it looks like we are forced to do it manually. Is this correct?

If I also go with option 2 from https://github.com/nextauthjs/adapters/issues/192#issuecomment-907668413 (which I did in the above release), then I'll have to find out how to do transactions to delete Sessions and Accounts when a user is deleted.
Because this is not necessarily atomic:
https://github.com/nextauthjs/adapters/blob/cf0e69f2d4fab984bff285830e35cd00ae46b740/packages/mongodb/src/index.ts#L87-L91

when I tried to create a transaction locally, I got the error: `Transaction numbers are only allowed on a replica set member or mongos`

**Comment by balazsorban44** [comment]
I just looked at the mongoDB example in the Next.js repo: https://github.com/vercel/next.js/blob/canary/examples/with-mongodb/lib/mongodb.js

I am guessing most people will have something similar setup, so I updated my PR to use this approach.

**Comment by italodeandra** [comment]
About the connections, you're right with your assumption of having to handle it by yourself. But the example on `vercel/next.js` is the same approach I did for my own project.
Mongoose also uses the same idea, but it also keeps more than one connection on an array `connections` if you have more than one database (with still the same fundamental idea). By looking on the PR I think it's fine.

Transactions are a little bit tricky. We grew having to handle inconsistency by ourselves. Transaction was introduced natively on MongoDB v4 so you can see we had plenty years doing differently.
On v4 Transaction came with two downsides, it did not support sharding and required replication. On v4.2 sharding started being supported but until now replication is still required, hence the message `only allowed on a replica set`.
Sadly, most of the tools available for installing MongoDB installs just a standalone server, you need to configure that by yourself and add `replicaSet=rs` to the connection string.

Here's how to convert an existing standalone server to a replica set: https://docs.mongodb.com/manual/tutorial/convert-standalone-to-replica-set/

I sadly still didn't implement the native transaction usage on my applications so since I lack the knowledge I'll fail to help you on that.

**Comment by italodeandra** [comment]
> I'm testing it now on my latest project.

It's working. For reference I'm testing  as following:

```json
    "next-auth": "4.0.0-next.24",
    "@next-auth/mongodb-adapter": "0.0.2-pr.193-b9ed40bc.279",
    "mongodb": "4.1.1",
```

**Comment by balazsorban44** [comment]
This is fixed through #193 and released in the `next` channel on npm. Going to let it be there for a while to get feedback from more people. I am going to release `next-auth@beta` later today!

**Comment by italodeandra** [comment]
I updated to `next`.

Is there a place I can follow to know when it's on `beta`? I found this repo to be a little bit confusing since it has all the adapters bundled together.

**Comment by balazsorban44** [comment]
It doesn't bundle adapters together, we use [Lerna](https://lerna.js.org) to manage versioning in our multi-package repository, which is a fairly common tool. Next.js and Material UI use it is as well, for instance.

I will admit, versioning is hard, and I wish I was an expert on it, but I kind of blindly trust what Lerna versioning gives us.

Once `next-auth` v4 is stable, I will promote all `next` adapters to stable as well if no bigger issues arise.

**Comment by italodeandra** [comment]
Yeah, I didn't mean it like a bad thing or to complain. The problem for me is what you mentioned, the versioning but also tags and releases. But if you say that `next-auth` is promoted together with `@next-auth/mongodb-adapter` then it's fine.

Thanks for your work ❤️

**Comment by balazsorban44** [comment]
Thank you for understanding! When I have the time, I will try to look into a better release flow, hopefully there exists an easier one 😅
